[package]
name = "jerboa"
version = "0.1.0"
edition = "2024"

[build-dependencies]
lalrpop = "0.22.2"

[dependencies]
ntest = "0.9.3"
lalrpop-util = { version = "0.21.0", features = ["lexer", "unicode"] }

